### ISSUE TITLE
Why hashing?

### ISSUE THREAD

**Issue by RamonYeung** [guestwalk/kaggle-2014-criteo#1]
I noticed your team have used a hashing method to map the features. But I can't figure out why and how.

That would be so nice if you guys can show me the way getting into it.

**Comment by guestwalk** [comment]
Why: We use hashing trick for convenience (we don't have to maintain a dictionary) and efficiency (the parallelization is easy).
How: You can find our hashing function in kaggle-2014-criteo/converters/common.py. The function name is "hashstr". It hashes any string into an integer.
