### ISSUE TITLE
pre-a.py 中target_cat_feats这些特征是怎么提取的？

### ISSUE THREAD

**Issue by RalphAdu** [guestwalk/kaggle-2014-criteo#2]
rt

**Comment by Tongzhenguo** [comment]
I have an error when make this project
[root@BGP-LF-1MF1243 kaggle-2014-criteo]# make
make -C solvers/gbdt
make[1]: Entering directory `/tmp/kaggle-2014-criteo/solvers/gbdt'
g++ -Wall -Wconversion -O2 -fPIC -std=c++0x -march=native -fopenmp -o gbdt src/train.cpp src/common.cpp src/timer.cpp src/gbdt.cpp
In file included from src/train.cpp:4:
src/common.h:1: warning: unknown option after ‘#pragma GCC diagnostic’ kind
In file included from src/gbdt.h:5,
                 from src/train.cpp:6:
src/common.h:1: warning: unknown option after ‘#pragma GCC diagnostic’ kind
In file included from src/common.cpp:7:
src/common.h:1: warning: unknown option after ‘#pragma GCC diagnostic’ kind
src/common.cpp: In function ‘uint32_t<unnamed>::get_nr_line(const std::string&)’:
src/common.cpp:19: error: ‘nullptr’ was not declared in this scope
src/common.cpp: In function ‘uint32_t<unnamed>::get_nr_field(const std::string&)’:
src/common.cpp:38: error: ‘nullptr’ was not declared in this scope
src/common.cpp: In function ‘void<unnamed>::read_dense(Problem&, const std::string&)’:
src/common.cpp:54: error: ‘nullptr’ was not declared in this scope
src/common.cpp: In function ‘void<unnamed>::sort_problem(Problem&)’:
src/common.cpp:86: error: no matching function for call to ‘sort(__gnu_cxx::__normal_iterator<Node*, std::vector<Node, std::allocator<Node> > >, __gnu_cxx::__normal_iterator<Node*, std::vector<Node, std::allocator<Node> > >, <unnamed>::sort_problem(Problem&)::sort_by_v)’
src/common.cpp: In function ‘void<unnamed>::read_sparse(Problem&, const std::string&)’:
src/common.cpp:103: error: ‘nullptr’ was not declared in this scope
src/common.cpp:120: error: ‘class std::vector<unsigned int, std::allocator<unsigned int> >’ has no member named ‘shrink_to_fit’
src/common.cpp:121: error: ‘class std::vector<long unsigned int, std::allocator<long unsigned int> >’ has no member named ‘shrink_to_fit’
src/common.cpp:131: error: expected initializer before ‘:’ token
src/common.cpp:133: warning: suggest parentheses around assignment used as truth value
src/common.cpp:134: error: expected primary-expression before ‘}’ token
src/common.cpp:134: error: expected ‘)’ before ‘}’ token
src/common.cpp:134: error: expected primary-expression before ‘}’ token
src/common.cpp:134: error: expected ‘;’ before ‘}’ token
In file included from src/gbdt.h:5,
                 from src/gbdt.cpp:7:
src/common.h:1: warning: unknown option after ‘#pragma GCC diagnostic’ kind
src/gbdt.cpp: In member function ‘float GBDT::predict(const float*) const’:
src/gbdt.cpp:366: error: expected initializer before ‘:’ token
src/gbdt.cpp:368: error: expected primary-expression before ‘return’
src/gbdt.cpp:368: error: expected ‘;’ before ‘return’
src/gbdt.cpp:368: error: expected primary-expression before ‘return’
src/gbdt.cpp:368: error: expected ‘)’ before ‘return’
make[1]: *** [gbdt] Error 1
make[1]: Leaving directory `/tmp/kaggle-2014-criteo/solvers/gbdt'
make: *** [gbdt] Error 2

**Comment by guestwalk** [comment]
they appear in the dataset more than 4 million times
