### ISSUE TITLE
hash trick collision

### ISSUE THREAD

**Issue by yangyiming1234** [guestwalk/kaggle-2014-criteo#4]
For example, feature i and feature j correspnd to the same position in the hash dimension. But feature i and feature j belong to different field. And that is to say, the data contains (field_i, hash_i,1),
(field_j, hash_j,1)，hash_i = hash_j. I think that one feature must belong to a field. Could this phenomenon happen? If so, does it have an effect on the model?

**Comment by guestwalk** [comment]
Yes it can happen. In practice I don't see a bad impact but I don't know any theoratically guarantee.
